# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='R_Bild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(max_length=500)),
                ('caption', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
