# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:19
from __future__ import unicode_literals

import app.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_bild',
            name='date',
            field=app.forms.FormattedDateField(),
        ),
    ]
