# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:59
from __future__ import unicode_literals

import app.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_r_objekt'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='R_Projektbild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(max_length=500)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('date', app.forms.FormattedDateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='r_bild',
            name='caption',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='r_bild',
            name='date',
            field=app.forms.FormattedDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='r_objekt',
            name='caption',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='r_objekt',
            name='date',
            field=app.forms.FormattedDateField(blank=True),
        ),
    ]
