# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:24
from __future__ import unicode_literals

import app.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_r_projektbild_projekt_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_Buch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('src', models.TextField(max_length=500)),
                ('img', models.TextField(max_length=500)),
                ('date', app.forms.FormattedDateField(blank=True)),
            ],
        ),
    ]
